name: CI

on:
  push: {}
  pull_request: {}
  schedule:
  - cron: "0 0 */1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install linting packages
      run: |
        npm install \
          awesome-lint \
          remark-cli \
          remark-lint \
          remark-lint-no-dead-urls
    - name: run awesome-lint
      run: npx awesome-lint readme.md
    - name: run awesome-lint
      run: |
        npx remark \
          -u remark-lint-no-dead-urls \
          readme.md
